### ISSUE TITLE
client disconnecting

### ISSUE THREAD

**Issue by emiel92** [KixAss/homebridge-ziggo-next#16]
Get this error every 5 seconds when the device is off. Is there a solution for?

Error: client disconnecting
    at MqttClient._checkDisconnecting (/usr/lib/node_modules/homebridge-ziggo-next/node_modules/mqtt/lib/client.js:389:26)
    at MqttClient.publish (/usr/lib/node_modules/homebridge-ziggo-next/node_modules/mqtt/lib/client.js:429:12)
    at ZiggoAccessory.getUiStatus (/usr/lib/node_modules/homebridge-ziggo-next/index.js:366:14)
    at ZiggoAccessory.updateZiggoState (/usr/lib/node_modules/homebridge-ziggo-next/index.js:374:7)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)

**Comment by clemensmol** [comment]
Experiencing the same issue. Haven't found a solution yet.

**Comment by jsiegenthaler** [comment]
My homebridge-eosstb has very solid session connections, try it...
