### ISSUE TITLE
mqttClient is not a function

### ISSUE THREAD

**Issue by ronaldmk** [KixAss/homebridge-ziggo-next#21]
I get this TypeError

Starting to advertise 'Homebridge 8039 5903' using bonjour-hap backend!
[29/08/2021, 08:10:10] Homebridge v1.3.4 (Homebridge 8039) is running on port 51077.
[29/08/2021, 08:10:11] TypeError: mqttClient.publish is not a function
    at ZiggoAccessory.getUiStatus (/usr/local/lib/node_modules/homebridge-ziggo-next/index.js:366:14)
    at ZiggoAccessory.updateZiggoState (/usr/local/lib/node_modules/homebridge-ziggo-next/index.js:374:7)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
[29/08/2021, 08:10:11] Got SIGTERM, shutting down Homebridge...
[29/08/2021, 08:10:17] TypeError: mqttClient.publish is not a function
    at ZiggoAccessory.getUiStatus (/usr/local/lib/node_modules/homebridge-ziggo-next/index.js:366:14)
    at ZiggoAccessory.updateZiggoState (/usr/local/lib/node_modules/homebridge-ziggo-next/index.js:374:7)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
[29/08/2021, 08:10:17] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[29/08/2021, 08:10:22] [HB Supervisor] Restarting Homebridge...

**Comment by jsiegenthaler** [comment]
You can try using [eosstb](https://github.com/jsiegenthaler/homebridge-eosstb) as an alternative plugin.

**Comment by ronaldmk** [comment]
Thank you. That works perfectly
