### ISSUE TITLE
mqtt error

### ISSUE THREAD

**Issue by remko2000** [KixAss/homebridge-ziggo-next#3]
After installing this plugin I get error (and sigterm):
TypeError: mqttClient.publish is not a function

What's the problem here?

**Comment by GuitarHer01** [comment]
I had the same issue. 
After I changed my Ziggo accoutname, the error was gone. 
I had an old username, from the UPC era. This was not an email address as with the current Ziggo usernames, but just a name with numbers and letters. So no email address.
The error was gone after I had an email address as Ziggo accountname.
Unfortunately I cannot turn the Next on or Off with the plugin, despite there are no errors anymore. ..

**Comment by mouragio** [comment]
Hi,
I have got the same error:

TypeError: mqttClient.publish is not a function
    at ZiggoAccessory.getUiStatus (/homebridge/node_modules/homebridge-ziggo-next/index.js:366:14)
    at ZiggoAccessory.updateZiggoState (/homebridge/node_modules/homebridge-ziggo-next/index.js:374:7)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)

On ziggo Go I have an emailadress I use with ziggo and vodafone (shared login).. cant change the login unfortunatelly.

Any other suggestions? I would love to have the mediabox next into my homekit config.. thanx

**Comment by ChristianPorsche** [comment]
Same problem

**Comment by Veldkornet** [comment]
Been getting this error all of a sudden, things won't startup anymore:

```
[8/27/2020, 7:48:06 PM] [Mediabox] getSession:  Error: connect ENETUNREACH 104.64.21.248:443 - Local (0.0.0.0:0)
[8/27/2020, 7:48:11 PM] TypeError: mqttClient.publish is not a function
    at ZiggoAccessory.getUiStatus (/homebridge/node_modules/homebridge-ziggo-next/index.js:366:14)
    at ZiggoAccessory.updateZiggoState (/homebridge/node_modules/homebridge-ziggo-next/index.js:374:7)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
[8/27/2020, 7:48:11 PM] Got SIGTERM, shutting down Homebridge...
[8/27/2020, 7:48:16 PM] TypeError: mqttClient.publish is not a function
    at ZiggoAccessory.getUiStatus (/homebridge/node_modules/homebridge-ziggo-next/index.js:366:14)
    at ZiggoAccessory.updateZiggoState (/homebridge/node_modules/homebridge-ziggo-next/index.js:374:7)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

**Comment by mouragio** [comment]
> Hi,
> I have got the same error:
> 
> TypeError: mqttClient.publish is not a function
> at ZiggoAccessory.getUiStatus (/homebridge/node_modules/homebridge-ziggo-next/index.js:366:14)
> at ZiggoAccessory.updateZiggoState (/homebridge/node_modules/homebridge-ziggo-next/index.js:374:7)
> at listOnTimeout (internal/timers.js:531:17)
> at processTimers (internal/timers.js:475:7)
> 
> On ziggo Go I have an emailadress I use with ziggo and vodafone (shared login).. cant change the login unfortunatelly.
> 
> Any other suggestions? I would love to have the mediabox next into my homekit config.. thanx

update... I tried once more to install the plugin.. first time.. it worked! altho the channel selection doenst follow the actual channel set (on the remote) but ok...

Once I restarted the homekit raspberry.. error again and homekit wouldnt start.. tried few times and it came up again... so its kinda like russian roulette if the plugin will load yes or no...

I do want this plugin badly to work (and better) so hopefully someone can improve this one. deleted the plugin for now,

**Comment by Veldkornet** [comment]
I eventually got this working... can't remember what solved it exactly. I think another plugin was causing a conflict maybe.
Or potentially an update to homebridge itself.
I currently have the following, running in my docker container:

Homebridge Version | 1.2.3
Node.js Version | v12.19.0
Npm Version | v6.14.8

**Comment by marinovdh** [comment]
I ran into the same problem. In my case I set my username/password incorrectly. After fixing it with the correct username/password in the config it worked well. 👍
