### ISSUE TITLE
TypeError: mqttClient.publish is not a function

### ISSUE THREAD

**Issue by Veldkornet** [KixAss/homebridge-ziggo-next#8]
Been getting this error all of a sudden, things won't startup anymore:

```
[8/27/2020, 7:48:06 PM] [Mediabox] getSession:  Error: connect ENETUNREACH 104.64.21.248:443 - Local (0.0.0.0:0)
[8/27/2020, 7:48:11 PM] TypeError: mqttClient.publish is not a function
    at ZiggoAccessory.getUiStatus (/homebridge/node_modules/homebridge-ziggo-next/index.js:366:14)
    at ZiggoAccessory.updateZiggoState (/homebridge/node_modules/homebridge-ziggo-next/index.js:374:7)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
[8/27/2020, 7:48:11 PM] Got SIGTERM, shutting down Homebridge...
[8/27/2020, 7:48:16 PM] TypeError: mqttClient.publish is not a function
    at ZiggoAccessory.getUiStatus (/homebridge/node_modules/homebridge-ziggo-next/index.js:366:14)
    at ZiggoAccessory.updateZiggoState (/homebridge/node_modules/homebridge-ziggo-next/index.js:374:7)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

**Comment by Veldkornet** [comment]
Seems like a duplicate of #3
